hard_tabs = true

max_width = 80
array_width = 25
chain_width = 50

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"

reorder_modules = true
reorder_imports = true

match_block_trailing_comma = true
overflow_delimited_expr = true
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20
